# Generated by Django 3.2 on 2021-04-21 01:28

from django.db import migrations, models
import django.db.models.deletion
import versatileimagefield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('neighbourhood', models.CharField(max_length=50)),
                ('street_and_number', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('birthdate', models.DateField()),
                ('phone', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopters', to='pawapi.address')),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('first_name_contact', models.CharField(max_length=255)),
                ('last_name_contact', models.CharField(max_length=255)),
                ('email_contact', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('donation_link', models.CharField(max_length=255)),
                ('web_address', models.CharField(max_length=255)),
                ('story', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associations', to='pawapi.address')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', versatileimagefield.fields.VersatileImageField(upload_to='media/', verbose_name='Image')),
                ('image_ppoi', versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], default='dog', max_length=50)),
                ('age', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=10)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=50)),
                ('character', models.CharField(choices=[('P', 'Playful'), ('S', 'Shy'), ('I', 'Independent'), ('F', 'Friendly'), ('N', 'Naughty'), ('L', 'Lazy')], default='P', max_length=30)),
                ('story', models.TextField(max_length=1000)),
                ('special_needs', models.TextField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='adopter_pets', to='pawapi.adopter')),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pawapi.association')),
                ('image', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='i_pets', to='pawapi.image')),
            ],
        ),
        migrations.AddField(
            model_name='association',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_associations', to='pawapi.image'),
        ),
        migrations.CreateModel(
            name='AdoptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pets_today', models.CharField(max_length=10)),
                ('which_pets_today', models.CharField(max_length=255)),
                ('amount_pets_past', models.CharField(max_length=10)),
                ('story_pets_past', models.TextField(max_length=1000)),
                ('everyone_agrees', models.BooleanField(default=False)),
                ('allowed_to_own', models.BooleanField(default=False)),
                ('if_change_address', models.TextField(max_length=1000)),
                ('average_age', models.CharField(max_length=255)),
                ('place_of_sleep', models.TextField(max_length=1000)),
                ('time_by_itself', models.TextField(max_length=1000)),
                ('petcare_awareness', models.TextField(max_length=1000)),
                ('pet_responsable', models.TextField(max_length=1000)),
                ('veterinarian', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_forms', to='pawapi.adopter')),
            ],
        ),
        migrations.AddField(
            model_name='adopter',
            name='image',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='i_adopters', to='pawapi.image'),
        ),
    ]
