# Generated by Django 3.2 on 2021-04-27 05:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Adopter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, null=True)),
                ('state', models.CharField(max_length=50, null=True)),
                ('city', models.CharField(max_length=50, null=True)),
                ('zip_code', models.CharField(max_length=20, null=True)),
                ('neighbourhood', models.CharField(max_length=50, null=True)),
                ('street_and_number', models.CharField(max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='adopters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Association',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name_contact', models.CharField(max_length=255)),
                ('last_name_contact', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('donation_link', models.CharField(max_length=255)),
                ('web_address', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('zip_code', models.CharField(max_length=20)),
                ('neighbourhood', models.CharField(max_length=50)),
                ('street_and_number', models.CharField(max_length=20)),
                ('story', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='associations', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('species', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog')], default='dog', max_length=50)),
                ('age', models.CharField(max_length=40)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='F', max_length=10)),
                ('size', models.CharField(choices=[('S', 'Small'), ('M', 'Medium'), ('L', 'Large')], default='S', max_length=50)),
                ('character', models.CharField(choices=[('P', 'Playful'), ('S', 'Shy'), ('I', 'Independent'), ('F', 'Friendly'), ('N', 'Naughty'), ('L', 'Lazy')], default='P', max_length=30)),
                ('story', models.TextField(max_length=1000)),
                ('special_needs', models.TextField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('association', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='pawapi.association')),
            ],
        ),
        migrations.CreateModel(
            name='AdoptionForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_pets_today', models.CharField(max_length=10)),
                ('which_pets_today', models.CharField(max_length=255)),
                ('amount_pets_past', models.CharField(max_length=10)),
                ('story_pets_past', models.TextField(max_length=1000)),
                ('everyone_agrees', models.BooleanField(default=False)),
                ('allowed_to_own', models.BooleanField(default=False)),
                ('if_change_address', models.TextField(max_length=1000)),
                ('average_age', models.CharField(max_length=255)),
                ('place_of_sleep', models.TextField(max_length=1000)),
                ('time_by_itself', models.TextField(max_length=1000)),
                ('petcare_awareness', models.TextField(max_length=1000)),
                ('pet_responsable', models.TextField(max_length=1000)),
                ('veterinarian', models.TextField(max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adopter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_forms', to='pawapi.adopter')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adoption_pets', to='pawapi.pet')),
            ],
        ),
    ]
