# Generated by Django 3.2 on 2021-05-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='occupation',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='adopter',
            name='story',
            field=models.TextField(max_length=1000, null=True),
        ),
    ]
