# Generated by Django 3.2 on 2021-05-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawapi', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='birthdate',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='adopter',
            name='ocupation',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='adopter',
            name='story',
            field=models.TextField(max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='adoptionform',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=50),
        ),
    ]
