# Generated by Django 3.2 on 2021-04-26 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawapi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adopter',
            name='birthdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='city',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='first_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='last_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='neighbourhood',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='phone',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='state',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='street_and_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='zip_code',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
