# Generated by Django 3.2 on 2021-05-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawapi', '0002_auto_20210505_1736'),
    ]

    operations = [
        migrations.AddField(
            model_name='adopter',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
    ]
