# Generated by Django 3.2 on 2021-05-07 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pawapi', '0002_auto_20210505_1834'),
        ('pawapi', '0003_adopter_birthdate'),
    ]

    operations = [
    ]
