# Generated by Django 3.2 on 2021-05-07 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawapi', '0004_merge_0002_auto_20210505_1834_0003_adopter_birthdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adopter',
            name='ocupation',
        ),
        migrations.AlterField(
            model_name='adopter',
            name='birthdate',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='adopter',
            name='story',
            field=models.TextField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='adoptionform',
            name='allowed_to_own',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='adoptionform',
            name='everyone_agrees',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='character',
            field=models.CharField(choices=[('Juguetón', 'Juguetón'), ('Miedoso', 'Miedoso'), ('Independiente', 'Independiente'), ('Amistoso', 'Amistoso'), ('Travieso', 'Travieos'), ('Flojo', 'Flojo')], default='Juguetón', max_length=30),
        ),
        migrations.AlterField(
            model_name='pet',
            name='gender',
            field=models.CharField(choices=[('Macho', 'Macho'), ('Hembra', 'Hembra')], default='Hembra', max_length=10),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(choices=[('Pequeño', 'Pequeño'), ('Mediano', 'Mediano'), ('Grande', 'Grande')], default='Pequeño', max_length=50),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.CharField(choices=[('gato', 'Gato'), ('perro', 'Perro')], default='dog', max_length=50),
        ),
    ]
